[pytest]
markers =
    fixtur: marks tests from 1_fixtures_vals_codeExplanation folder
    mockdata: marks tests from 2_MockData folder
    standalone: marks tests from 3_StandAlone_tests folder
    webapi: marks tests from 4_webapi_with_JSON_and_APIClass folder
    webapi_params: marks tests from 5_webapi_with_JSON_APIClass_and_PARAMS folder
    pageobject: marks tests from 6_TCs_with_classes_PageObject folder
    bdd: marks tests from 7_BDD_Cucumber_Features folder
    iphonex: marks tests from 8_iPhoneX_test folder
    bdd_iphonex: marks tests from 9_BDD_iPhoneX folder
